// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr5uHCC5iqnddH6_VO30-JCB9vb6f20Zs',
    appId: '1:540249503070:android:02a08c80fe7b88957c4bcf',
    messagingSenderId: '540249503070',
    projectId: 'personalitytest-c1e9a',
    databaseURL: 'https://personalitytest-c1e9a-default-rtdb.firebaseio.com',
    storageBucket: 'personalitytest-c1e9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3SyyS5VTuzjEfVgiyr9Iacqh2fBmw7QI',
    appId: '1:540249503070:ios:35ff62de4442f1827c4bcf',
    messagingSenderId: '540249503070',
    projectId: 'personalitytest-c1e9a',
    databaseURL: 'https://personalitytest-c1e9a-default-rtdb.firebaseio.com',
    storageBucket: 'personalitytest-c1e9a.firebasestorage.app',
    iosBundleId: 'com.example.personalitytest',
  );

}